// SPDX-License-Identifier: MIT
// Copyright (c) Microsoft Corporation. All rights reserved.

/**
 * src/services/event_service.cpp
 */

#include "redfish_sdk/services/event_service.hpp"
#include "redfish_sdk/transport/auth.hpp"
#include "../internal/logger.hpp"
#include <nlohmann/json.hpp>
#include <chrono>
#include <iomanip>
#include <sstream>

namespace redfish {

static std::string iso8601_now() {
    auto now = std::chrono::system_clock::now();
    auto t   = std::chrono::system_clock::to_time_t(now);
    std::ostringstream ss;
    ss << std::put_time(std::gmtime(&t), "%Y-%m-%dT%H:%M:%SZ");
    return ss.str();
}

EventServiceHandle::EventServiceHandle(
    IHttpClient&                             http,
    const AuthState&                         auth_state,
    const std::map<std::string, std::string>& discovery_map
)
    : http_(http), auth_state_(auth_state), discovery_map_(discovery_map)
{}

std::string EventServiceHandle::service_uri() const {
    auto it = discovery_map_.find("EventService");
    return it != discovery_map_.end() ? it->second : "/redfish/v1/EventService";
}

RedfishResponse EventServiceHandle::get_service_info() {
    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto raw = http_.request("GET", service_uri(), headers);
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

RedfishResponse EventServiceHandle::subscribe(
    const std::string&              destination,
    const std::vector<std::string>& event_types,
    const std::vector<std::string>& registry_prefixes,
    const std::vector<std::string>& message_ids,
    const std::vector<std::string>& resource_types,
    const std::string&              event_format_type,
    const std::string&              context,
    const std::string&              protocol,
    const std::string&              subscription_type
) {
    nlohmann::json body = {
        {"Destination",      destination},
        {"Protocol",         protocol},
        {"SubscriptionType", subscription_type},
    };
    if (!event_types.empty())       body["EventTypes"]       = event_types;
    if (!registry_prefixes.empty()) body["RegistryPrefixes"] = registry_prefixes;
    if (!message_ids.empty())       body["MessageIds"]       = message_ids;
    if (!resource_types.empty())    body["ResourceTypes"]    = resource_types;
    if (!event_format_type.empty()) body["EventFormatType"]  = event_format_type;
    if (!context.empty())           body["Context"]          = context;

    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto subs_uri = service_uri() + "/Subscriptions";
    auto raw = http_.request("POST", subs_uri, headers, body.dump());
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

RedfishResponse EventServiceHandle::list_subscriptions() {
    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto raw = http_.request("GET", service_uri() + "/Subscriptions", headers);
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

RedfishResponse EventServiceHandle::get_subscription(const std::string& uri) {
    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto raw = http_.request("GET", uri, headers);
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

RedfishResponse EventServiceHandle::delete_subscription(const std::string& uri) {
    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto raw = http_.request("DELETE", uri, headers);
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

RedfishResponse EventServiceHandle::submit_test_event(const nlohmann::json& event_data) {
    nlohmann::json default_body = {
        {"EventType",      "Alert"},
        {"EventId",        "1"},
        {"EventTimestamp", iso8601_now()},
        {"Severity",       "OK"},
        {"Message",        "Test event generated by Redfish Client SDK."},
        {"MessageId",      "Base.1.8.GeneralError"},
    };

    nlohmann::json body = default_body;
    if (!event_data.is_null()) {
        for (auto& [k, v] : event_data.items())
            body[k] = v;
    }

    std::map<std::string, std::string> headers;
    AuthManager::attach_auth(auth_state_, headers);
    auto action_uri = service_uri() + "/Actions/EventService.SubmitTestEvent";
    auto raw = http_.request("POST", action_uri, headers, body.dump());
    return build_response(raw.status_code, raw.headers, raw.body_text);
}

} // namespace redfish
